# This workflow builds and deploys to github-pages on merge with main

name: Deploy to github page
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
          uses: actions/checkout@v2
          run: npm install
      - name: Build
          run: npm run build
      - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            publish_branch: gh-pages
